#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Sep 10 23:23:40 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
